name: lumica_app
description: "Lumica - Your AI-powered mental wellness companion. Track moods, journal thoughts, and connect with professional counselors."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6
  
  # Storage
  flutter_secure_storage: ^9.0.0
  get_storage: ^2.1.1
  
  # UI & Theming
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  
  # Backend & API
  supabase_flutter: ^2.8.0
  google_generative_ai: ^0.4.6
  flutter_dotenv: ^6.0.0
  
  # Utilities
  intl: ^0.20.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  uuid: ^4.5.1
  
  # Rich Text & Media
  flutter_quill: ^11.5.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  image: ^4.0.17
  
  # Networking
  internet_connection_checker_plus: ^2.9.1+1
  
  # UI Components
  shimmer: ^3.0.0
  
  # Charts
  fl_chart: ^0.69.0
  
  # Animation packages
  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_native_splash: ^2.4.7
  lottie: ^3.3.2
  permission_handler: ^12.0.1
  share_plus: ^10.1.3
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env
