name: lumica_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  google_fonts: ^6.3.2
  get_storage: ^2.1.1
  flutter_screenutil: ^5.9.3
  intl: ^0.20.0
  supabase_flutter: ^2.8.0
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_quill: ^11.5.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_dotenv: ^6.0.0
  internet_connection_checker_plus: ^2.9.1+1
  google_generative_ai: ^0.4.6
  uuid: ^4.5.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - .env
